### ISSUE TITLE
Blank plot

### ISSUE THREAD

**Issue by JohnCoene** [BristolMyersSquibb/blockr#281]
Plots render but blank.

```r
devtools::load_all()

corrplot_block <- function(data, ...) {
  fields <- list(
    method = new_select_field("circle", choices= c("circle", "square", "ellipse", "number", "shade", "color", "pie")),
    type = new_select_field("full", choices= c("full", "lower", "upper")),
    order = new_select_field("original",choices= c("original", "AOE", "FPC", "hclust", "alphabet")),
    title = new_string_field()
  )
  new_block(
    fields = fields,
    expr = quote({
      corr_matrix <- data |>
        dplyr::select_if(is.numeric) |>
        purrr::discard(~ all(is.na(.))) |>  # removed those column which have all NA Values
        na.omit() |>  # removed the rows containing na values
        stats::cor()

      corrplot::corrplot(corr_matrix, method = .(method), type = .(type),
                         order = .(order), addrect = 2, tl.col = "black", tl.srt = 45,
                         diag = FALSE,
                         title = .(title)
      ) #
    }),
    ...,
    class = c("corrplot_block", "plot_block")
  )
}

stack <- new_stack(
  data_block,
  corrplot_block
)

library(shiny)

ui <- fluidPage(
  theme = bslib::bs_theme(version = 5),
  generate_ui(stack)
)

server <- function(input, output, session) {
  generate_server(stack)
}

shinyApp(ui, server)
```

![image](https://github.com/blockr-org/blockr/assets/7833796/bd979b04-2227-4e02-a6fb-c533078b03ec)

**Comment by JohnCoene** [comment]
Locally resetting back it seems to me that is introduce here https://github.com/blockr-org/blockr/commit/a57bee1988a1932383d89082ae252e3254e5cb03

Previous commit from the day before works https://github.com/blockr-org/blockr/commit/0a4696821d9c48992131c69ab66bfbf6bd72dfd4

**Comment by JohnCoene** [comment]
@DivadNojnarg @nbenn let me know what you see. I feel a bit funny because what I see above seems true on my machine but hardly see how said commit could break that.

**Comment by nbenn** [comment]
@JohnCoene not sure what this means, but with current main (https://github.com/blockr-org/blockr/commit/5ea91f491031b7a2ea505c64eee92118f244186f) I get

<img width="1487" alt="Screenshot 2024-02-08 at 13 04 12" src="https://github.com/blockr-org/blockr/assets/3158446/94f942bc-d5d2-4e1c-9333-464b07c82543">

which I assume is what I should expect, no? Is it possible you're working with an earlier state of the repo? Or that in your setup the plot output is redirected somewhere it is not captured by the app?

**Comment by JohnCoene** [comment]
That works with `BLOCKR_DEV = TRUE` but otherwise renders blank on my screen.

**Comment by DivadNojnarg** [comment]
@nbenn I am in between: sometines I see the plot in the app.

<img width="691" alt="Screenshot 2024-02-08 at 12 57 44" src="https://github.com/blockr-org/blockr/assets/18291543/1a7c5eb1-df0b-418a-8692-9a137182761a">

However, sometimes the plot draws in a separate VSCode window, leaving the app block empty.

**Comment by JohnCoene** [comment]
@DivadNojnarg interesting, when I run the example from the command line with `Rscript` or just pasting the code in the R console it creates a `Rplots.pdf` locally and/or shows it in a separate window.

![image](https://github.com/blockr-org/blockr/assets/7833796/61bb1371-2422-44c7-aa8c-aaf16266d3e8)

**Comment by nbenn** [comment]
@JohnCoene I don't fully understand what is happening, but

```r
stack <- new_stack(
  data_block,
  corrplot_block
)
```

seems to write a first version of the plot to the default device at that point and then later on, updates get sent there as well. I would assume if you did not set up the stack beforehand but add from within the running app, the plots should get properly captured. Or does that also not work as expected?

**Comment by JohnCoene** [comment]
I'm afraid not, I get the same issue.

```r
devtools::load_all()

corrplot_block <- function(data, ...) {
  fields <- list(
    method = new_select_field("circle", choices= c("circle", "square", "ellipse", "number", "shade", "color", "pie")),
    type = new_select_field("full", choices= c("full", "lower", "upper")),
    order = new_select_field("original",choices= c("original", "AOE", "FPC", "hclust", "alphabet")),
    title = new_string_field()
  )
  new_block(
    fields = fields,
    expr = quote({
      corr_matrix <- data |>
        dplyr::select_if(is.numeric) |>
        purrr::discard(~ all(is.na(.))) |>  # removed those column which have all NA Values
        na.omit() |>  # removed the rows containing na values
        stats::cor()

      corrplot::corrplot(corr_matrix, method = .(method), type = .(type),
                         order = .(order), addrect = 2, tl.col = "black", tl.srt = 45,
                         diag = FALSE,
                         title = .(title)
      ) #
    }),
    ...,
    class = c("corrplot_block", "plot_block")
  )
}

stack <- new_stack(
  data_block
)

library(shiny)

ui <- fluidPage(
  theme = bslib::bs_theme(version = 5),
  actionButton("add", "Add"),
  generate_ui(stack)
)

server <- function(input, output, session) {
  nb <- eventReactive(input$add, {
     list(
      block = corrplot_block,
      position = NULL
    )
  })
  generate_server(stack, new_block = nb)
}

shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
Did someone take a look at this? I want to make sure I isolate the correct commit.

> Locally resetting back it seems to me that is introduced here https://github.com/blockr-org/blockr/commit/a57bee1988a1932383d89082ae252e3254e5cb03
> 
> Previous commit from the day before works https://github.com/blockr-org/blockr/commit/0a4696821d9c48992131c69ab66bfbf6bd72dfd4

**Comment by nbenn** [comment]
So my first approach failed. In line with what you report above @JohnCoene. It does not seem to matter where the plot goes when instantiating the stack.

**Comment by JohnCoene** [comment]
I think I'm nearing a fix.

**Comment by nbenn** [comment]
That's good to hear. I'm running out of ideas tbh.

**Comment by JohnCoene** [comment]
Apologies, I was sure I got it working but it seems not, looking into it yet again

**Comment by nbenn** [comment]
For me your fix works. Or what new problem pops up?

**Comment by JohnCoene** [comment]
It's fixed for rendering an existing stack with a plot block at the end but it's not working when adding blocks (see example in comment higher)

**Comment by JohnCoene** [comment]
@DivadNojnarg would you have any ideas, I'm now totally out of ideas as to what could be going wrong here. The UI should be generated the same way as an initial render.

**Comment by JohnCoene** [comment]
Having tried the revert again I'm fairly confident it's in https://github.com/blockr-org/blockr/commit/0a4696821d9c48992131c69ab66bfbf6bd72dfd4 

Reverting to commits prior to this we can render the plot block fine, statically or dynamically, after that commit it no longer works.

@DivadNojnarg would you have any idea what might have caused this?

**Comment by DivadNojnarg** [comment]
I check the history of my comments and I found:

```r
} else {
        reactive({
          req(is_valid$block)
          if (is.null(in_dat())) {
          if (is.null(in_dat()) && !inherits(x, "transform_block")) {
```

> @nbenn I did not notice but the block server refactor introduced an issue. At this line, it is possible to have evaluate a transform block without data parameter, leading to an error when calling evaluate_block (evaluate_block.transform_block expects a data parameter). generate_code_server is not a generic so we lost the ability to tackle this is in a clean way. I have to add !inherits(x, "transform_block" to continue my PR but we will have the same issue with plot blocks I think.

I had found an issue here and this is likely affecting plots as well.

**Comment by DivadNojnarg** [comment]
I tested with `be8fc242182beb9a6435f8ee44fd6661a0e458b3` (older than https://github.com/blockr-org/blockr/commit/0a4696821d9c48992131c69ab66bfbf6bd72dfd4) and the plot don't show. I still need to go backward.

**Comment by nbenn** [comment]
@DivadNojnarg @JohnCoene no fix yet, but something interesting: with a `brwose()`r in `server_output.plot_block()` I get not a plot object, but a data frame.

**Comment by JohnCoene** [comment]
Hah, looks like @nbenn is onto something :)!

**Comment by nbenn** [comment]
Ok, I finally do have something. But it's a mess. Not sure how stable this is. On the plus side we just provide generic implementations, so no core changes required to make it work.

```r
devtools::load_all()

new_corrplot_block <- function(data, ...) {
  fields <- list(
    method = new_select_field("circle", choices= c("circle", "square", "ellipse", "number", "shade", "color", "pie")),
    type = new_select_field("full", choices= c("full", "lower", "upper")),
    order = new_select_field("original", choices= c("original", "AOE", "FPC", "hclust", "alphabet")),
    title = new_string_field()
  )
  new_block(
    fields = fields,
    expr = quote(
      (function(x) x |>
        dplyr::select_if(is.numeric) |>
        purrr::discard(~ all(is.na(.))) |>  # removed those column which have all NA Values
        na.omit() |>  # removed the rows containing na values
        stats::cor() |>
        corrplot::corrplot(method = .(method), type = .(type),
                         order = .(order), addrect = 2, tl.col = "black", tl.srt = 45,
                         diag = FALSE,
                         title = .(title))
      )()
    ),
    ...,
    class = c("corrplot_block", "plot_block")
  )
}

corrplot_block <- function(data, ...) {
  initialize_block(new_corrplot_block(data, ...), data)
}

.S3method("evaluate_block", "corrplot_block", function(x, data, ...) {
  structure(generate_code(x), data = data)
})

.S3method("server_output", "corrplot_block", function(x, result, output) {
  shiny::renderPlot({
    res <- result()
    eval(
      substitute(data %>% expr, list(expr = res)),
      list(data = attr(res, "data"))
    )
  })
})

stack <- new_stack(
  data_block
)

ui <- shiny::fluidPage(
  theme = bslib::bs_theme(version = 5),
  shiny::actionButton("add", "Add"),
  generate_ui(stack)
)

server <- function(input, output, session) {
  nb <- shiny::eventReactive(input$add, {
     list(
      block = corrplot_block,
      position = NULL
    )
  })
  generate_server(stack, new_block = nb)
}

shiny::shinyApp(ui, server)
```

**Comment by nbenn** [comment]
I think what is happening is the following: `corrplot::corrplot()` returns some list and produces a plot as a side effect. This now means, it is crucial, that the `corrplot::corrplot()` call is evaluated inside `shiny::renderPlot()` which generally is not the case (this happens in `evaluate_block()`).

Now thanks to lazy eval, in some cases, `evaluate_block()` might actually be run from within `server_output()`, which I think is why it sometimes did work and in others did not (not super sure here).

So what I'm basically doing here is forcing actual eval to happen later than blockr thinks it should be done. The framework was more build with a ggplot-style setup I presume, where you create an object that can emit a plot at a later time. I guess we might need to make some changes if we want to support base plotting infrastructure better.

**Comment by nbenn** [comment]
@JohnCoene does this help you?

**Comment by JohnCoene** [comment]
You're a magician @nbenn! 

So the issue is not plot block but corrrplot itself, I had not even thought of this.

Just did a few simple tests and it appears to be solved now.

Thanks again!

**Comment by nbenn** [comment]
@JohnCoene I checked and the change in https://github.com/blockr-org/blockr/pull/282/commits/2d634e6f4ca42997eca9232e4234f059506589b6 technically is no longer needed, as without (and making sure that the plot is rendered at the right time) works in both the examples we have. I don't mind if you feel what we have is better now, just pointing out that in case this was more of a quick-fix, we could revert it.

Thinking about this a bit more, something like

```r
.S3method("evaluate_block", "corrplot_block", function(x, data, ...) {
  file <- tempfile(fileext = ".png")

  dev <- shiny:::startPNG(file, 400, 400, 72)
  on.exit(grDevices::dev.off(dev))

  res <- NextMethod()

  structure(res, file = file)
})

.S3method("server_output", "corrplot_block", function(x, result, output) {
  shiny::renderImage({
    list(src = attr(result(), "file"), alt = "This is alternate text")
  }, deleteFile = TRUE)
})
```

would in principle be much nicer. The problem with that is the hard-coded image dimensions at eval-time. Apparently we might be able to extract dimensions dynamically from `session$clientData`, but we'd need to know the full ID to properly look that up there.

**Comment by nbenn** [comment]
@DivadNojnarg @JohnCoene final suggestion for the day (finally something that might be workable beyond the current scope)

```r
.S3method("evaluate_block", "corrplot_block", function(x, data, ...) {
  structure(NextMethod(), plot = grDevices::recordPlot())
})

.S3method("server_output", "corrplot_block", function(x, result, output) {
  shiny::renderPlot(grDevices::replayPlot(attr(result(), "plot")))
})
```

This gives you the proper result (if you want to add a block that consumes the return value of `corrplot::corrplot()` while giving a resizable plot.
