### ISSUE TITLE
Update companion packages

### ISSUE THREAD

**Issue by JohnCoene** [BristolMyersSquibb/blockr#390]
As far as I can tell all packages that were built for the previous version of blockr are now broken, e.g.: blockr.extra

**Comment by DivadNojnarg** [comment]
@JohnCoene I can do the update.

**Comment by DivadNojnarg** [comment]
@JohnCoene: I noticed blockr.echart4r was developed using block.generate. Does it make sense to update `block.generate` and then regenerate the package or manually update blockr.echart4r?

**Comment by JohnCoene** [comment]
I'll take this package
