### ISSUE TITLE
Add block ui - improve

### ISSUE THREAD

**Issue by JohnCoene** [BristolMyersSquibb/blockr#403]
We should improve the add block ui so that either:

1. Only blocks that can be added to the stack are displayed
2. Blocks that cannot be added to the stack are greyed out

Suggestion from  @karmatarap 

I think it's a good idea, it'd make it easier to navigate the numerous blocks we will eventually have.

**Comment by christophsax** [comment]
https://github.com/blockr-org/blockr/pull/325
