### ISSUE TITLE
Broken join block

### ISSUE THREAD

**Issue by JohnCoene** [BristolMyersSquibb/blockr#441]
Join block is broken as far as I can tell.

 @DivadNojnarg is it needed for workshop?

```r
library(blockr)
library(shiny)

dat1_stack <- new_stack(
  new_dataset_block(selected = "iris"),
  name = "dat1",
  title = "First dataset"
)

dat2_stack <- new_stack(
  new_dataset_block(selected = "iris"),
  name = "dat2",
  title = "Second dataset"
)

merged_stack <- new_stack(
  new_result_block("dat1"),
  new_join_block(y = "dat2", type = "left", by = "Species")
)

ui <- fluidPage(
  theme = bslib::bs_theme(5L),
  div(
    class = "row",
    div(
      class = "col-md-6",
      generate_ui(dat1_stack)
    ),
    div(
      class = "col-md-6",
      generate_ui(dat2_stack)
    )
  ),
  generate_ui(merged_stack)
)

server <- function(input, output, session) {
  generate_server(dat1_stack)
  generate_server(dat2_stack)
  generate_server(merged_stack)
}

shinyApp(ui, server)
```

**Comment by DivadNojnarg** [comment]
Yes that's a consequence of the result block issue in #439 and #432. We don't need it for the workshop but that's still high priority.

**Comment by JohnCoene** [comment]
@DivadNojnarg which version should I revert to so that it works? I need to deploy a demo app with joins.

**Comment by DivadNojnarg** [comment]
I did not released the very latest main so you can use this one: https://github.com/BristolMyersSquibb/blockr/releases/tag/v0.0.2.9023.

**Comment by karmatarap** [comment]
@DivadNojnarg. Please can we fix this as a priority as it is one of the key selling points for the demos (PhuUSE EU + internal)

**Comment by nbenn** [comment]
This is the same issue as #432 and is being addressed with highest priority. I'm closing here in favor of #432.
